core:
  server:
    url: localhost:8082
server:
  port: 8085
logging:
  level:
    com:
      zaxxer: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework: INFO
      springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg traceID=%X{trace_id} %n'
oracle:
  jdbc:
    Trace: true
    driver:
      level: DEBUG
    pool:
      level: DEBUG
    util:
      level: DEBUG
  level: DEBUG
  sql:
    level: DEBUG
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connectionTimeout: 500
      initializationFailTimeout: 1
    password: Esp3Jb0s
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(HOST=srvsicaborad01)(PORT=1521)(PROTOCOL=tcp))(CONNECT_DATA=(SERVICE_NAME=dbd.agbar.ga.local)))
    username: ESPDJBOS
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: CMRPADM
    show-sql: true